---

# play 1 configuring Cisco Router 1 Syed

- name: Configuring Cisco router 1
  hosts: Cisco1
  gather_facts: false

  tasks:
    - name: Setting up OSPF on Cisco Router Syed
      ios_config:
        lines:
          - router ospf 1
          - router-id 10.1.1.1
          - network 192.168.122.2 0.0.0.0 area 0

    - name: Show running configuration on Router Syed
      ios_command:
        commands:
          - show run
      register: config

    - name: Backing up router Syed configurations
      copy:
        content: "{{ config.stdout[0] }}"
        #The lookup('env', 'GITHUB_WORKSPACE') will get the name of the path the git runner uses to execute the playbook
        #The ansible script then places the configuration file in the runners corresponding /ansible/backups directory 
        #so that the runner can directly commit the files to GitHub repo
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/ansible/backups/Syed_config.txt" 

#play 2 configuring Cisco Router 2 Ali

- name: Configuring Cisco router 2
  hosts: Cisco2
  gather_facts: false

  tasks:
    - name: Setting up OSPF on Cisco Router Ali
      ios_config:
        lines:
          - router ospf 1
          - router-id 10.2.2.2
          - network 192.168.122.3 0.0.0.0 area 0

    - name: Show running configuration on Router Ali
      ios_command:
        commands:
          - show run
      register: config

    - name: Backing up router Ali configurations
      copy:
        content: "{{ config.stdout[0]}}"
        dest: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/ansible/backups/Ali_config.txt"
