name: Network Automation

on:
  # Trigger on push to main
  push:
    branches: [ "main"]

jobs:
  configure-network:
    runs-on: self-hosted

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.PAT }}

          ANSIBLE_HOST_KEY_CHECKING: False

        run: |
          ansible-playbook ansible/configure_devices.yml  -i ansible/inventory.ini --extra-vars "ansible_user=${USERNAME} ansible_password=${PASSWORD}"


      - name: Commit and Push Backup
        run: |
          git add .
          git commit -m "Automated running-config backup commit" || echo "no changes to commit"
          git push ${{ secrets.PAT }}


