name: Network Automation

on:
  # Trigger on push to main
  push:
    branches: [ "main" ]
    paths:
      - 'ansible/**'
      - '.github/workflows/network_automation.yml'


jobs:
  configure-network:
    runs-on: self-hosted

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }
          TOKEN: ${{ secrets.PAT }}

          ANSIBLE_HOST_KEY_CHECKING: False

        run: |
          ansible-playbook ansible/configure_devices.yml  -i ansible/inventory.ini

      - name: Commit and Push Backup
        run: |
          git config --global user.name "Syed"
          git config --global user.email "ali431@sheridancollege.ca"
          git add ansible/backups
          git commit -m "Automated running-config backup commit" || echo "no changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/SyedAli431/network-automation-lab.git



