name: Network Automation

on:
  # Trigger on push to main
  push:
    branches: [ "main" ]
    paths:
      - 'ansible/**'
      - '.github/workflows/network_automation.yml'
jobs:
  configure-network:
    runs-on: self-hosted 

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
          
      - name: change directory
        run: cd /etc/ansible/

      - name: Run Ansible Playbook
        env:
          #create variables that store git action secret credentials
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.PAT }}

          #ensures Ansible does not use SSH key authentication 
          ANSIBLE_HOST_KEY_CHECKING: False

        run: |
          #specifiy the playbook name and inventory file to use along with passing credentials to connect to Cisco devices
          ansible-playbook ansible/configure_devices.yml  -i ansible/inventory.ini --extra-vars "ansible_user=${USERNAME} ansible_password=${PASSWORD}"

      - name: Commit and Push Backup
        run: |
          git config --global user.name "Syed"
          git config --global user.email "ali431@sheridancollege.ca"
          git add ansible/backups
          git commit -m "Automated running-config backup commit" || echo "no changes to commit"
          git push


